//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders_Kazanim
    {
        public int Id { get; set; }
        public string Ders_Kodu { get; set; }
        public string Ders_Ogrenme { get; set; }
    
        public virtual Dersler Dersler { get; set; }
    }
}
