//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Fakulte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fakulte()
        {
            this.Acilan_Dersler = new HashSet<Acilan_Dersler>();
            this.Sinav_Sonuclari = new HashSet<Sinav_Sonuclari>();
        }
        [Display(Name = "Fakülte Numarasý")]
        [Required(ErrorMessage = "Fakülte Numarasý boþ geçilemez...")]
        public string Fakulte_No { get; set; }
        [Display(Name = "Fakülte Adý")]
        [Required(ErrorMessage = "Fakülte Adý boþ geçilemez...")]
        public string Fakulte_Adi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acilan_Dersler> Acilan_Dersler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinav_Sonuclari> Sinav_Sonuclari { get; set; }
    }
}
