//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru_Kazanim
    {
        public int Id { get; set; }
        public string Soru_Cevabi { get; set; }
        public string Ogrenci_Cevabi { get; set; }
        public string Kazanim { get; set; }
    }
}
